## Docker Compose requires an .env file
## .env for security reasons is not part of the repo
## .env will be dynamically created on CI/CD process
# dFile='Dockerfile'
# appName='someapp'
# PORT_MAPPED=5000
# PORT_TARGET=5001
# ENV=DEV|UAT|PROD
# REDIS_PORT=6379
#

services:
  db:
    container_name: ${appName}_mongo
    image: mongo
    command: mongod --port ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    # volumes:
    #   - "./docker/mongodb/data:/data/db"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    restart: always
    networks:
      - default

  # cache:
  #   container_name: ${appName}_redis
  #   image: redis:alpine
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   volumes:
  #     - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   networks:
  #     - default
  #   ports:
  #     - 6379:6379

  api:
    container_name: ${appName}_api
    build:
      context: .
      dockerfile: ./docker/${dFile}
    volumes:
      - "./src:/app/src"
    expose:
      - 3000
      - 8080
    ports:
      - "${PORT_MAPPED}:${PORT_TARGET}"
      - 9229:9229
    environment:
      DEBUG: ${DEBUG}
      PORT_MAPPED: ${PORT_MAPPED}
      PORT_TARGET: ${PORT_TARGET}
      SWAGGER_TITLE: "Visa Identity"
      SWAGGER_DESCR: "Swagger"
      SWAGGER_VS: "1.0.0"
      MONGOOSEHOST: db
      MONGOOSEPORT: ${MONGO_PORT}
      MONGOOSEUSER: ${MONGO_USER}
      MONGOOSEPASS: ${MONGO_PASS}
      MONGOOSEDB: ${MONGO_DB}
      MONGOOSETLSCERT: ${MONGOOSETLSCERT}
      # REDISHOST: ${appName}_redis
      # REDISPORT: 6379
      MODE: ${NODE_ENV}
      RUN_MIGRATIONS: "true"
      GIPSRS: ${GIPSRS}
      GIPSUA: ${GIPSUA}
      BIOSERVER: ${BIOSERVER}
      WEBBIO: ${WEBBIO}
      IDEMIA_HOST: ${IDEMIA_HOST}
      ENV: ${ENV}
      PLAID_CLIENTID: ${PLAID_CLIENTID}
      PLAID_SECRET: ${PLAID_SECRET}
      PLAID_HOST: ${PLAID_HOST}
      ONFIDO_TOKEN: ${ONFIDO_TOKEN}
      ONFIDO_HOST: ${ONFIDO_HOST}
      PUBLIC_KEY: ${PUBLIC_KEY}
    depends_on:
      - db
    links:
      - db
    networks:
      - default
networks:
  default:
    name: ${appName}_orchestrator
    driver: bridge
version: '3.5'
